import { Contract, Token } from '../../types/configs';
import CurvePool010Abi from '../abi/curve/pool-0.1.0.json';
import CurvePool024Abi from '../abi/curve/pool-0.2.4.json';
import CurvePool028Abi from '../abi/curve/pool-0.2.8.json';
import CurvePool0212Abi from '../abi/curve/pool-0.2.12.json';
import CurvePool0215Abi from '../abi/curve/pool-0.2.15.json';
import CurvePool030Abi from '../abi/curve/pool-0.3.0.json';
import CurvePool031Abi from '../abi/curve/pool-0.3.1.json';
import { Tokens } from '../constants';

export interface CurvePool extends Contract {
  // meta pools are pool which coin pair with 3crv pool (USDC, USDT, DAI)
  isMetaPool: boolean;

  tokens: Array<Token>; // match index value on contract
}

export const CurveContracts: Array<CurvePool> = [
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool024Abi,
    address: '0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7',
    birthday: 16308190,
    isMetaPool: false,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne', 'RemoveLiquidityImbalance'],
    tokens: [Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool0212Abi,
    address: '0xd51a44d3fae010294c616388b506acda1bfaae46',
    birthday: 16308190,
    isMetaPool: false,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.USDT, Tokens.ethereum.WBTC, Tokens.ethereum.WETH],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xdc24316b9ae028f1497c275eb9192a3ea0f67022',
    birthday: 16308190,
    isMetaPool: false,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.ETH, Tokens.ethereum.stETH],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool031Abi,
    address: '0xdcef968d416a41cdac0ed8702fac8128a64241a2',
    birthday: 16308190,
    isMetaPool: false,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne', 'RemoveLiquidityImbalance'],
    tokens: [Tokens.ethereum.FRAX, Tokens.ethereum.USDC],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool030Abi,
    address: '0x8301ae4fc9c624d1d396cbdaa1ed877821d7c511',
    birthday: 16308190,
    isMetaPool: false,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.WETH, Tokens.ethereum.CRV],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool010Abi,
    address: '0xa5407eae9ba41422680e2e00537571bcc53efbfd',
    birthday: 16308190,
    isMetaPool: false,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityImbalance'],
    tokens: [Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT, Tokens.ethereum.sUSD],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xd632f22692fac7611d2aa1c0d552930d43caed3b',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.FRAX, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xc9c32cd16bf7efb85ff14e0c8603cc90f6f2ee49',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.BEAN, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xed279fdd11ca84beef15af5d39bb4d4bee23f0ca',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.LUSD, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0x4f062658eaaf2c1ccf8c8e36d6824cdf41167956',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.GUSD, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0x5a6a4d54456819380173272a5e8e9b9904bdf41b',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.MIM, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xdebf20617708857ebe4f679508e7b7863a8a8eee',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.aDAI, Tokens.ethereum.aUSDC, Tokens.ethereum.aUSDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool0215Abi,
    address: '0x828b154032950c8ff7cf8085d841723db2696056',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.WETH, Tokens.ethereum.stETH],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool0215Abi,
    address: '0xa1f8a6807c402e4a15ef4eba36528a3fed24e577',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.NativeCoin, Tokens.ethereum.frxETH],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool0215Abi,
    address: '0x9d0464996170c6b9e75eed71c68b99ddedf279e8',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.CRV, Tokens.ethereum.cvxCRV],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool031Abi,
    address: '0xb576491f1e6e5e62f1d8f26062ee822b40b0e0d4',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.WETH, Tokens.ethereum.CVX],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool031Abi,
    address: '0xb30da2376f63de30b42dc055c93fa474f31330a5',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.alUSD, Tokens.ethereum.FRAX, Tokens.ethereum.USDC],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool031Abi,
    address: '0x9409280dc1e6d33ab7a8c6ec03e5763fb61772b5',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.WETH, Tokens.ethereum.LDO],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool0215Abi,
    address: '0x9848482da3ee3076165ce6497eda906e66bb85c5',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.NativeCoin, Tokens.ethereum.pETH],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xecd5e75afb02efa118af914515d6521aabd189f1',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.TUSD, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0x43b4fdfd4ff969587185cdb6f0bd875c5fc83f8c',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'TokenExchangeUnderlying', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.alUSD, Tokens.ethereum.DAI, Tokens.ethereum.USDC, Tokens.ethereum.USDT],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool028Abi,
    address: '0xc4c319e2d4d66cca4464c0c2b32c9bd23ebe784e',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.NativeCoin, Tokens.ethereum.alETH],
  },
  {
    chain: 'ethereum',
    protocol: 'curve',
    abi: CurvePool031Abi,
    address: '0xc26b89a667578ec7b3f11b2f98d6fd15c07c54ba',
    birthday: 16308190,
    isMetaPool: true,
    events: ['TokenExchange', 'AddLiquidity', 'RemoveLiquidity', 'RemoveLiquidityOne'],
    tokens: [Tokens.ethereum.WETH, Tokens.ethereum.YFI],
  },
];
