import { ProtocolConfig } from '../types/configs';
import {
  Aavev1Configs,
  Aavev2Configs,
  Aavev3Configs,
  AbracadabraConfigs,
  AgilityConfigs,
  AirswapConfigs,
  AnkrConfigs,
  ApecoinConfigs,
  ArrakisConfigs,
  AurafinanceConfigs,
  BalancerConfigs,
  BancorConfigs,
  BeanstalkConfigs,
  BeefyConfigs,
  BinanceStakedEthConfigs,
  BlurConfigs,
  BungeeConfigs,
  CarbonConfigs,
  ChaiConfigs,
  ChainlinkConfigs,
  CompoundConfigs,
  Compoundv3Configs,
  ConicConfigs,
  ConvexConfigs,
  CowswapConfigs,
  CrvusdConfigs,
  CurveConfigs,
  DefisaverConfigs,
  DodoConfigs,
  EnsConfigs,
  Eth2Configs,
  EulerConfigs,
  ExactlyConfigs,
  FraxethConfigs,
  FraxlendConfigs,
  FraxswapConfigs,
  GearboxConfigs,
  HopConfigs,
  KyberswapAggregatorConfigs,
  KyberswapClassicConfigs,
  LidoConfigs,
  LiquityConfigs,
  LooksrareConfigs,
  LoopringConfigs,
  LybraConfigs,
  MakerConfigs,
  MetamaskConfigs,
  MorphoConfigs,
  MultichainConfigs,
  OpenseaConfigs,
  PancakeswapConfigs,
  PancakeswapV3Configs,
  ParaswapConfigs,
  PendleConfigs,
  RaftConfigs,
  RaribleConfigs,
  RocketpoolConfigs,
  ShibaswapConfigs,
  SiloConfigs,
  SparkConfigs,
  StakewiseConfigs,
  StargateConfigs,
  SturdyConfigs,
  SushiConfigs,
  Sushiv3Configs,
  SwellConfigs,
  TornadocashConfigs,
  Uniswapv2Configs,
  Uniswapv3Configs,
  X2y2Configs,
  YearnConfigs,
  ZeroxConfigs,
} from './protocols';

export const ParserVersion = '1.0.1';

// return initial block for worker syncing
export const WorkerGenesisBlocks: { [key: string]: number } = {
  ethereum: 16308190, // Jan-01-2023 12:00:11 AM +UTC
};

export const ApiQueryLogsCachingTime = 10 * 60; // 10 minutes
export const ApiQueryLogsLimitDefault = 1000;

export const MetricDailyStats = 'dailystats';
export const MetricSnapshotStats = 'snapshotStats'; // per day

export const AllProtocols: Array<ProtocolConfig> = [
  Uniswapv2Configs,
  Uniswapv3Configs,
  CompoundConfigs,
  Compoundv3Configs,
  Aavev1Configs,
  Aavev2Configs,
  Aavev3Configs,
  BalancerConfigs,
  RocketpoolConfigs,
  CurveConfigs,
  CrvusdConfigs,
  CowswapConfigs,
  LidoConfigs,
  SushiConfigs,
  Sushiv3Configs,
  PancakeswapConfigs,
  PancakeswapV3Configs,
  BancorConfigs,
  AurafinanceConfigs,
  ConvexConfigs,
  CarbonConfigs,
  EnsConfigs,
  HopConfigs,
  MultichainConfigs,
  ShibaswapConfigs,
  FraxethConfigs,
  FraxswapConfigs,
  FraxlendConfigs,
  LooksrareConfigs,
  LoopringConfigs,
  OpenseaConfigs,
  BlurConfigs,
  BeanstalkConfigs,
  X2y2Configs,
  Eth2Configs,
  ChainlinkConfigs,
  ZeroxConfigs,
  ParaswapConfigs,
  YearnConfigs,
  TornadocashConfigs,
  EulerConfigs,
  LiquityConfigs,
  AbracadabraConfigs,
  MakerConfigs,
  SparkConfigs,
  StargateConfigs,
  SiloConfigs,
  BeefyConfigs,
  ApecoinConfigs,
  GearboxConfigs,
  RaribleConfigs,
  ExactlyConfigs,
  StakewiseConfigs,
  ConicConfigs,
  KyberswapClassicConfigs,
  KyberswapAggregatorConfigs,
  ArrakisConfigs,
  LybraConfigs,
  PendleConfigs,
  BinanceStakedEthConfigs,
  AgilityConfigs,
  DodoConfigs,
  MorphoConfigs,
  ChaiConfigs,
  AnkrConfigs,
  DefisaverConfigs,
  MetamaskConfigs,
  AirswapConfigs,
  BungeeConfigs,
  RaftConfigs,
  SturdyConfigs,
  SwellConfigs,
];
